# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Naturaily
email: hello@naturaily.com
description: > # this means to ignore newlines until "baseurl:"
  Agile web and mobile development team building Ruby on Rails, React and
  React Native applications for startups and enterprises. Letâ€™s talk!
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://naturaily.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: naturaily
github_username:  naturaily
highlighter: rouge
pagination:
  enabled: true
  per_page: 5
  permalink: '/:num/'
  indexpage: 'index'
  sort_reverse: true
collections:
  career:
    output: true
    permalink: /join/:path
  portfolio:
    output: true
    permalink: /project/:path
  services:
    output: true
    permalink: /services/index.html
  authors:
    output: true
    permalink: blog/authors/:path

blog:
  tags:
    url: /blog/tags/
    title_prefix: " "
    layout: tag.html
  categories:
    url: /blog/categories/
    title_prefix: " "
    layout: category.html
  authors:
    url: /blog/authors/
    title_prefix: " "
    layout: author.html


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      comments: true
      description: ' '
      category: ' '
      author: ' '
      tags: ' '
      image: ' '
      text-preview: ' '
  -
    scope:
      path: ''
      type: 'career'
    values:
      layout: 'career-details'
      description: ' '
      type: ' '
      salary: ' '
      requirements: '   '
      responsibilities: '   '
      offer: '   '
      benefits: '   '
      salary-range: '   '
  -
    scope:
      path: ''
      type: 'services'
    values:
      layout: 'services'

include:
  - _redirects

permalink: /blog/:title

# Build settings

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.txt
  - README.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
